### ISSUE TITLE
significant differences with samtools flagstat output

### ISSUE THREAD

**Issue by wangduo-ux** [wdecoster/cramino#33]
Hello，
 
I recently used cramino to perform QC for long reads data (BAM), and found the alignment rates from cramino and samtools flagstats function are very different. For example, cramino got 60%, but the samtools got 98%.

Can you help me explain the reasons for such a difference?

Best regard

**Comment by wdecoster** [comment]
Hi,

Thanks for reporting this, I will look into this difference. Which cramino version did you use?

Wouter

**Comment by wangduo-ux** [comment]
Hi, Wouter,


Thanks for your reply. I used the version 0.15.0.


For example, the output of cramino for a BAM show a alignment rate of  59.64%
But samtools flagstat shows a alignment rate of 99.35% 


 



Best regard,
Duo Wang
| |
Duo Wang
|
|
***@***.***
|
---- Replied Message ----
| From | Wouter De ***@***.***> |
| Date | 11/7/2024 15:51 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [wdecoster/cramino] significant differences with samtools flagstat output (Issue #33) |

Hi,

Thanks for reporting this, I will look into this difference. Which cramino version did you use?

Wouter

**Comment by wdecoster** [comment]
I have identified at least a part of the issue, as too many reads are used as denominator in that calculations. Did you also set a length filter? Because that would also contribute tot the difference.

**Comment by wdecoster** [comment]
Aha, from those numbers I see the difference. You get 6798047 by subtracting the number of secondary reads from the number of aligned reads.
samtools flagstat appears to calculate the alignment rate counting the secondary reads for both the numerator and the denominator. I am not sure if that is desirable.

Since the last cramino release, which I believe is not entirely correct, secondary reads are only counted for the denominator. I'll get that fixed.

**Comment by wangduo-ux** [comment]
Oh my god, I didn't notice this. So the cramino prints the primary alignment rates. Thanks for your patient reply.
